# Comprehensive configuration for lens dataset generation
# This config works with both synthetic and deeplenstronomy backends

# ============================================================================
# GENERAL SETTINGS
# ============================================================================
General:
  n_train: 1800                 # Number of training images (total)
  n_test: 200                   # Number of test images (total)  
  image_size: 64                # Image size in pixels (square images)
  seed: 42                      # Random seed for reproducibility
  balance: 0.5                  # Fraction of lens class (0.5 = balanced dataset)
  
  # Optional: specify exact counts instead of balance
  # n_train_lens: 900
  # n_train_nonlens: 900
  # n_test_lens: 100
  # n_test_nonlens: 100

# ============================================================================
# NOISE CONFIGURATION
# ============================================================================
Noise:
  gaussian_sigma: 0.02          # Standard deviation of Gaussian noise (0-1 scale)
  poisson_strength: 0.0         # Poisson noise strength (0.0 = disabled)
  
  # Advanced noise options (synthetic backend only)
  background_level: 0.01        # Background noise level
  readout_noise: 5.0           # CCD readout noise (electrons)

# ============================================================================
# LENS ARC PARAMETERS (for synthetic lens images)
# ============================================================================
LensArcs:
  min_radius: 8                 # Inner radius of Einstein ring (pixels)
  max_radius: 20                # Outer radius of Einstein ring (pixels)
  arc_width_min: 2              # Minimum arc thickness (pixels)
  arc_width_max: 4              # Maximum arc thickness (pixels)
  min_arcs: 1                   # Minimum number of arcs per image
  max_arcs: 3                   # Maximum number of arcs per image
  blur_sigma: 1.0               # Gaussian blur applied to arcs
  
  # Advanced arc parameters
  brightness_min: 0.7           # Minimum arc brightness (0-1)
  brightness_max: 1.0           # Maximum arc brightness (0-1)
  asymmetry: 0.2                # Arc asymmetry factor (0 = symmetric)

# ============================================================================
# GALAXY BLOB PARAMETERS (for synthetic non-lens images)
# ============================================================================
GalaxyBlob:
  sigma_min: 2.0                # Minimum galaxy size (pixels)
  sigma_max: 6.0                # Maximum galaxy size (pixels)
  ellipticity_min: 0.0          # Minimum ellipticity (0 = circular)
  ellipticity_max: 0.6          # Maximum ellipticity (0.6 = quite elongated)
  blur_sigma: 0.6               # Gaussian blur applied to galaxy
  
  # Advanced galaxy parameters
  brightness_min: 0.6           # Minimum galaxy brightness
  brightness_max: 1.0           # Maximum galaxy brightness
  sersic_index_min: 1.0         # Minimum Sersic index (1 = exponential)
  sersic_index_max: 4.0         # Maximum Sersic index (4 = de Vaucouleurs)

# ============================================================================
# DEEPLENSTRONOMY-SPECIFIC SETTINGS (when using deeplenstronomy backend)
# ============================================================================
DeepLenstronomy:
  # Observation parameters
  pixel_scale: 0.1              # arcsec/pixel
  exposure_time: 5400.0         # seconds
  magnitude_zero_point: 25.0    # AB magnitude zero point
  
  # Survey simulation
  survey_name: "HST"            # Survey to simulate (HST, LSST, Euclid, etc.)
  filter_name: "F814W"          # Filter/band name
  
  # Lens model configuration
  lens_models:
    - "SIE"                     # Singular Isothermal Ellipsoid
    - "SHEAR"                   # External shear (optional)
  
  # Source light model
  source_models:
    - "SERSIC"                  # Sersic profile
  
  # Lens light model (optional)
  lens_light_models:
    - "SERSIC"                  # Lens galaxy light
  
  # Parameter ranges for lens mass
  lens_mass:
    einstein_radius_min: 0.5    # arcsec
    einstein_radius_max: 2.0    # arcsec
    ellipticity_min: 0.0
    ellipticity_max: 0.3
  
  # Parameter ranges for source light
  source_light:
    magnitude_min: 20.0         # AB magnitude
    magnitude_max: 24.0         # AB magnitude
    size_min: 0.1               # arcsec (effective radius)
    size_max: 0.8               # arcsec
    sersic_index_min: 1.0
    sersic_index_max: 4.0

# ============================================================================
# OUTPUT CONFIGURATION
# ============================================================================
Output:
  # Directory structure options
  create_class_subdirs: true    # Create lens/ and nonlens/ subdirectories
  create_split_subdirs: true    # Create train/ and test/ subdirectories
  
  # File naming
  lens_prefix: "lens"           # Prefix for lens image filenames
  nonlens_prefix: "nonlens"     # Prefix for non-lens image filenames
  
  # Image format
  image_format: "PNG"           # PNG, JPEG, or FITS
  image_quality: 95             # JPEG quality (if using JPEG)
  
  # CSV options
  include_metadata: false       # Include extra columns in CSV (size, brightness, etc.)
  relative_paths: true          # Use relative paths in CSV files

# ============================================================================
# VALIDATION AND QUALITY CONTROL
# ============================================================================
Validation:
  enable_checks: true           # Enable automatic validation
  min_brightness: 0.01          # Minimum image brightness
  max_brightness: 1.0           # Maximum image brightness
  check_image_stats: true       # Compute and log image statistics
  
  # Quality metrics
  snr_threshold: 5.0            # Minimum signal-to-noise ratio
  contrast_threshold: 0.1       # Minimum contrast for features

# ============================================================================
# DEBUGGING AND LOGGING
# ============================================================================
Debug:
  verbose: true                 # Enable verbose logging
  save_intermediate: false      # Save intermediate processing steps
  plot_samples: false           # Generate sample plots (requires matplotlib)
  log_parameters: true          # Log all generated parameters
  
  # Error handling
  continue_on_error: true       # Continue generation if individual images fail
  max_retries: 3                # Maximum retries for failed images
