# ============================================================================
# DEEPLENSTRONOMY CONFIGURATION FOR GRAVITATIONAL LENSING SIMULATIONS
# ============================================================================
# This configuration creates realistic gravitational lens datasets using
# the official DeepLenstronomy package with proper physics-based modeling.

# ============================================================================
# GENERAL SIMULATION PARAMETERS
# ============================================================================
general:
  numPix: 64                    # Image size (64x64 pixels)
  deltaPix: 0.1                 # Pixel scale (arcsec/pixel)
  read_noise: 10.0              # Read noise (electrons)
  exp_time: 5400.0              # Exposure time (seconds)
  sky_brightness: 20.1          # Sky brightness (mag/arcsec²)
  num_exposures: 1              # Number of exposures
  background_noise: true        # Include background noise

# ============================================================================
# LENS MODEL PARAMETERS
# ============================================================================
lens_model:
  - 'SIE'                       # Singular Isothermal Ellipsoid (main lens)
  - 'SHEAR'                     # External shear (large-scale structure)

# ============================================================================
# SOURCE MODEL PARAMETERS (Background Galaxy)
# ============================================================================
source_model:
  - 'SERSIC_ELLIPSE'            # Sersic profile galaxy

# ============================================================================
# LENS LIGHT MODEL (Lens Galaxy)
# ============================================================================
lens_light_model:
  - 'SERSIC_ELLIPSE'            # Lens galaxy light profile

# ============================================================================
# PARAMETER DISTRIBUTIONS
# ============================================================================
distributions:
  # Lens parameters
  theta_E: [0.8, 2.5]           # Einstein radius (arcsec) - range for strong lenses
  e1_lens: [-0.2, 0.2]          # Lens ellipticity x-component
  e2_lens: [-0.2, 0.2]          # Lens ellipticity y-component
  gamma_ext: [0.0, 0.1]         # External shear strength
  psi_ext: [0, 180]             # External shear angle (degrees)
  
  # Source parameters
  R_sersic: [0.3, 1.2]          # Source galaxy size (arcsec)
  n_sersic: [1.0, 4.0]          # Sersic index (1=exponential, 4=de Vaucouleurs)
  e1_source: [-0.5, 0.5]        # Source ellipticity x-component
  e2_source: [-0.5, 0.5]        # Source ellipticity y-component
  amp_source: [0.5, 2.0]        # Source brightness amplitude
  
  # Lens light parameters
  R_sersic_lens_light: [1.0, 4.0]  # Lens galaxy size (arcsec)
  n_sersic_lens_light: [2.0, 4.0]  # Lens galaxy Sersic index
  e1_lens_light: [-0.3, 0.3]       # Lens light ellipticity x
  e2_lens_light: [-0.3, 0.3]       # Lens light ellipticity y
  amp_lens_light: [0.1, 1.0]       # Lens light brightness

# ============================================================================
# DATASET GENERATION PARAMETERS
# ============================================================================
dataset:
  num_samples: 100              # Number of lens images to generate
  output_path: "data_deeplenstronomy"
  image_format: "PNG"           # Output image format
  save_parameters: true         # Save simulation parameters
  random_seed: 42               # For reproducibility

# ============================================================================
# ADVANCED SIMULATION OPTIONS
# ============================================================================
advanced:
  psf_type: "GAUSSIAN"          # Point spread function type
  psf_fwhm: 0.1                 # PSF full width half maximum (arcsec)
  add_noise: true               # Add realistic noise
  noise_type: "POISSON"         # Noise model type
