# Lightning Ensemble Configuration
# Configuration for training ensemble models

# Model configuration
model:
  model_type: "ensemble"
  architectures: ["resnet18", "resnet34", "vit_b_16"]  # Multiple architectures
  pretrained: true
  dropout_rate: 0.5
  bands: 3
  ensemble_strategy: "uncertainty_weighted"
  physics_weight: 0.1
  uncertainty_estimation: true
  compile_model: false

# Training configuration
training:
  epochs: 40
  batch_size: 64
  learning_rate: 3e-4
  weight_decay: 1e-4
  scheduler_type: "cosine"
  warmup_epochs: 5

# Hardware configuration
hardware:
  devices: 2  # Use multiple GPUs for ensemble
  accelerator: "gpu"
  precision: "16-mixed"
  strategy: "ddp"

# Data configuration
data:
  # Local dataset
  data_root: "data/processed"
  val_split: 0.1
  
  # Data loading
  num_workers: 8
  image_size: 224
  augment: true
  pin_memory: true
  persistent_workers: true

# Logging configuration
logging:
  log_dir: "logs/ensemble"
  checkpoint_dir: "checkpoints/ensemble"
  use_wandb: true
  wandb_project: "gravitational-lens-ensemble"
  
  # Monitoring
  monitor: "val/auroc"
  mode: "max"
  patience: 12

# Reproducibility
reproducibility:
  seed: 42
  deterministic: true
  benchmark: false

# Ensemble-specific configurations
ensemble:
  # Individual model training
  train_individual: true
  individual_epochs: 30
  
  # Ensemble combination
  combination_method: "weighted_average"
  uncertainty_weighting: true
  
  # Model selection
  model_selection:
    min_individual_auroc: 0.85
    max_models: 5
