# Minimal, beginner-friendly config for generating a small toy dataset.
# The images are simple but lens-like (curved arcs) vs non-lens (elliptical blobs).
# You can safely change these numbers if you want a bigger dataset later.

General:
  n_train: 1800          # how many training images total (lens + non-lens)
  n_test: 200            # how many test images total
  image_size: 64         # pixels (keep small for speed)
  seed: 42               # make results reproducible
  balance: 0.5           # fraction of "lens" class (0.5 -> balanced)

Noise:
  # These control simple noise added to the images (for realism).
  gaussian_sigma: 0.02   # standard deviation of Gaussian noise (0..1 scale)
  poisson_strength: 0.0  # 0.0 disables Poisson noise; increase if you want

LensArcs:
  # Parameters for drawing 1–3 curved arcs (mimicking lensed arcs/rings).
  min_radius: 8          # inner radius in pixels
  max_radius: 20         # outer radius in pixels
  arc_width_min: 2       # line thickness (min) in pixels
  arc_width_max: 4       # line thickness (max) in pixels
  min_arcs: 1            # number of arcs per image (min)
  max_arcs: 3            # number of arcs per image (max)
  blur_sigma: 1.0        # blur after drawing arcs (in pixels)

GalaxyBlob:
  # Parameters for non-lens "galaxy-like" blobs (elliptical Gaussians).
  sigma_min: 2.0         # minor-axis sigma (pixels)
  sigma_max: 6.0         # minor-axis sigma (pixels)
  ellipticity_min: 0.0   # 0 = round
  ellipticity_max: 0.6   # 0.6 = quite elongated
  blur_sigma: 0.6        # small blur for realism
